### ISSUE TITLE
copy and paste cards between gko files

### ISSUE THREAD

**Issue by afenc** [gingko/client#184] opened 2019-12-20 12:41 UTC
Sometimes we need to reuse cards in different files. 
Gingko 2.4.7 on Mac 10.15.2.

**Comment by AdrianoFerrari** [comment] 2019-12-30 00:26
Thanks for the input :slightly_smiling_face: .
I'll close this issue though, since it's a duplicate of an existing one (#154).

**Closed** 2019-12-30 00:26 UTC
Labels: duplicate
